### ISSUE TITLE
pendulum-lab screen icons have incorrect aspect ratio

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/pendulum-lab#107]
Failure in requirejs mode with assertions enabled. Stack trace below.  Noted during a run of test-server.

```
Uncaught Error: Assertion failed: NavigationBar icons for screen 0 did not have a valid aspect ratio.
Error: Assertion failed: NavigationBar icons for screen 0 did not have a valid aspect ratio.
    at window.assertions.assertFunction (http://localhost/~cmalley/Github/assert/js/assert.js:22:13)
    at new NavigationBar (http://localhost/~cmalley/Github/joist/js/NavigationBar.js?bust=1440519811208:73:93)
    at new Sim (http://localhost/~cmalley/Github/joist/js/Sim.js?bust=1440519811208:369:25)
    at http://localhost/~cmalley/Github/pendulum-lab/js/pendulum-lab-main.js?bust=1440519811208:41:15
    at doneLoadingImages (http://localhost/~cmalley/Github/joist/js/SimLauncher.js?bust=1440519811208:31:9)
    at Object.launch (http://localhost/~cmalley/Github/joist/js/SimLauncher.js?bust=1440519811208:51:9)
    at http://localhost/~cmalley/Github/pendulum-lab/js/pendulum-lab-main.js?bust=1440519811208:40:15
    at Object.context.execCb (http://localhost/~cmalley/Github/sherpa/lib/require-2.1.11.js:1650:25)
    at Object.Module.check (http://localhost/~cmalley/Github/sherpa/lib/require-2.1.11.js:866:35)
    at Object. (http://localhost/~cmalley/Github/sherpa/lib/require-2.1.11.js:1113:20)
```

**Comment by jonathanolson** [comment]
Looks like increasing the width from 688 to 694 will be the closest for the 1.47 aspect ratio (but 693 is the closest for the 1.4691689 aspect ratio for the home-screen size).

To keep it centered, I'll try padding 3 pixels on each side first.

**Comment by jonathanolson** [comment]
Still an issue in automated testing. Will plan to resolve soon.
